# Generated by Django 5.0.7 on 2024-07-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invenory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('supplierName', models.CharField(max_length=100)),
                ('supplierEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('customerName', models.CharField(max_length=100)),
                ('customerPhone', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(to='invenory.invenory')),
            ],
        ),
    ]
