# Generated by Django 5.0.7 on 2024-07-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invenory', '0003_orderitem_alter_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='prodct',
            new_name='product',
        ),
    ]
