# Generated by Django 5.0.7 on 2024-07-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invenory', '0005_alert_stockalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
